# Generated by Django 6.0.6 on 2026-06-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_producto_imagen_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
